# Gwen - She is meant to check the answer generated by the Fox Club / Selina.
# She does not execute tasks like Julie, nor access the filesystem or external tools.
# She reviews reasoning for hallucinations and flawed logic.

from dataclasses import dataclass
from typing import Any, Protocol


class CriticBackend(Protocol):
    # Backends must turn Gwen's review messages into a text response.
    def generate(self, messages: list[dict[str, str]]) -> str:
        ...


class OllamaCriticBackend:
    def __init__(self, client: Any):
        # Keep the chat client used to request a critique.
        self.client = client

    def generate(self, messages: list[dict[str, str]]) -> str:
        # Ask Ollama to review the supplied conversation.
        response = self.client.chat(messages)

        try:
            # Support the response shapes commonly returned by chat clients.
            if isinstance(response, dict):
                if "message" in response and isinstance(response["message"], dict):
                    return response["message"]["content"]
                if "messages" in response:
                    messages_payload = response["messages"]
                    if isinstance(messages_payload, list) and messages_payload:
                        return messages_payload[0].get("content", "")
                    if isinstance(messages_payload, dict):
                        return messages_payload.get("content", "")
                if "content" in response:
                    return response["content"]
        except (KeyError, TypeError, AttributeError) as exc:
            # Surface malformed backend data instead of returning a misleading review.
            raise RuntimeError("[Gwen]: Invalid response from critic backend.....") from exc

        # Reject unknown response formats explicitly.
        raise RuntimeError("[Gwen]: Invalid response from critic backend.....")


@dataclass(frozen=True)
class GwenResult:
    # Store Gwen's decision, the reviewed reasoning, and her explanation.
    approved: bool
    reasoning: str
    critique: str


class Gwen:
    # Tell the critic what to inspect and prevent it from taking actions.
    SYSTEM_PROMPT = """
    You are Gwen, the critic agent inside Mates Helper.

    Your job is to critically review both Julie's reasoning and Selina's execution.

    You will receive:
    - The original user request
    - Julie's expanded task, plan, and uncertainty
    - Selina's interpretation, action, success status, result, and error

    Check for:
    - logical mistakes in Julie's plan
    - missing assumptions
    - incomplete reasoning
    - contradictions between Julie's plan and Selina's execution
    - unsafe actions
    - invalid conclusions
    - unnecessary or incorrect steps
    - whether Selina's execution matched Julie's plan
    - whether Selina's result is consistent with the expected outcome

    You must decide whether the reasoning and execution are acceptable.

    Return EXACTLY this format:

    APPROVED: true
    CRITIQUE: <your explanation>

    or:

    APPROVED: false
    CRITIQUE: <your explanation>

    Rules:
    - Do not execute tools.
    - Do not access files.
    - Do not browse the internet.
    - Do not perform external actions.
    - Do not rewrite the user's request.
    - Do not create an execution plan for Selina.
    - Review both Julie's reasoning and Selina's execution result.
    """.strip()

    def __init__(self, backend: CriticBackend):
        # Use the configured backend to generate the review.
        self.backend = backend

    def review(self, user_input: str, reasoning: str) -> GwenResult:
        # Validate both pieces of input before sending them to the critic.
        if not isinstance(user_input, str):
            raise TypeError("[Gwen]: User input must be a string.")

        if not isinstance(reasoning, str):
            raise TypeError("[Gwen]: Reasoning must be a string.")

        user_input = user_input.strip()
        reasoning = reasoning.strip()

        # Do not ask the backend to review missing user context.
        if not user_input:
            return GwenResult(
                approved=False,
                reasoning=reasoning,
                critique="User input is empty.",
            )

        # Do not approve or reject an absent reasoning response.
        if not reasoning:
            return GwenResult(
                approved=False,
                reasoning=reasoning,
                critique="Julie returned empty reasoning.",
            )

        # Build the isolated prompt containing only the request and reasoning to review.
        messages = [
            {
                "role": "system",
                "content": self.SYSTEM_PROMPT,
            },
            {
                "role": "user",
                "content": (
                    f"User request:\n"
                    f"{user_input}\n\n"
                    f"Julie's reasoning:\n"
                    f"{reasoning}"
                ),
            },
        ]

        # Generate Gwen's review without executing any tools or actions.
        result = self.backend.generate(messages)

        # The backend contract requires a text response.
        if not isinstance(result, str):
            raise TypeError("[Gwen]: Backend must return a string.....")

        result = result.strip()

        # Treat an empty backend response as a failed review.
        if not result:
            return GwenResult(
                approved=False,
                reasoning=reasoning,
                critique="Gwen returned an empty review",
            )

        # Extract the required decision and explanation from Gwen's response.
        approved = self._parse_approval(result)
        critique = self._parse_critique(result) or result

        # Return both the parsed fields and the original reasoning for traceability.
        return GwenResult(
            approved=approved,
            reasoning=reasoning,
            critique=critique,
        )

    @staticmethod
    def _parse_approval(result: str) -> bool:
        # Find the APPROVED line and accept only an explicit "true" value.
        for line in result.splitlines():
            normalized = line.strip().lower()
            if normalized.startswith("approved:"):
                value = normalized.split(":", 1)[1].strip()
                return value == "true"
        # Missing or unrecognized approval markers are treated as rejection.
        return False

    @staticmethod
    def _parse_critique(result: str) -> str:
        # Extract the explanation after the CRITIQUE marker.
        for line in result.splitlines():
            normalized = line.strip().lower()
            if normalized.startswith("critique:"):
                return line.split(":", 1)[1].strip()
        # Let the caller fall back to the complete backend response.
        return ""
