# Gwen - She is meant to check the answer generated by the Fox Club / Selina.
# She does not execute tasks like Julie, nor access the filesystem or external tools.
# She reviews reasoning for hallucinations and flawed logic.

from dataclasses import dataclass
from typing import Any, Protocol


class CriticBackend(Protocol):
    def generate(self, messages: list[dict[str, str]]) -> str:
        ...


class OllamaCriticBackend:
    def __init__(self, client: Any):
        self.client = client

    def generate(self, messages: list[dict[str, str]]) -> str:
        response = self.client.chat(messages)

        try:
            if isinstance(response, dict):
                if "message" in response and isinstance(response["message"], dict):
                    return response["message"]["content"]
                if "messages" in response:
                    messages_payload = response["messages"]
                    if isinstance(messages_payload, list) and messages_payload:
                        return messages_payload[0].get("content", "")
                    if isinstance(messages_payload, dict):
                        return messages_payload.get("content", "")
                if "content" in response:
                    return response["content"]
        except (KeyError, TypeError, AttributeError) as exc:
            raise RuntimeError("[Gwen]: Invalid response from critic backend.....") from exc

        raise RuntimeError("[Gwen]: Invalid response from critic backend.....")


@dataclass
class GwenResult:
    approved: bool
    reasoning: str
    critique: str


class Gwen:
    SYSTEM_PROMPT = """
    You are Gwen, the critic agent inside Mates Helper.

    Your job is to critically review reasoning produced by Julie.

    Check for:
    - logical mistakes
    - missing assumptions
    - incomplete reasoning
    - contradictions
    - unsafe actions
    - invalid conclusions
    - unnecessary or incorrect steps

    You must decide whether Julie's reasoning is acceptable.

    Return EXACTLY this format:

    APPROVED: true
    CRITIQUE: <your explanation>

    or:

    APPROVED: false
    CRITIQUE: <your explanation>

    Rules:
    - Do not execute tools.
    - Do not access files.
    - Do not browse the internet.
    - Do not perform external actions.
    - Do not rewrite the user's request.
    - Do not create an execution plan for Selina.
    - Only review Julie's reasoning.
    """.strip()

    def __init__(self, backend: CriticBackend):
        self.backend = backend

    def review(self, user_input: str, reasoning: str) -> GwenResult:
        if not isinstance(user_input, str):
            raise TypeError("[Gwen]: User input must be a string.")

        if not isinstance(reasoning, str):
            raise TypeError("[Gwen]: Reasoning must be a string.")

        user_input = user_input.strip()
        reasoning = reasoning.strip()

        if not user_input:
            return GwenResult(
                approved=False,
                reasoning=reasoning,
                critique="User input is empty.",
            )

        if not reasoning:
            return GwenResult(
                approved=False,
                reasoning=reasoning,
                critique="Julie returned empty reasoning.",
            )

        messages = [
            {
                "role": "system",
                "content": self.SYSTEM_PROMPT,
            },
            {
                "role": "user",
                "content": (
                    f"User request:\n"
                    f"{user_input}\n\n"
                    f"Julie's reasoning:\n"
                    f"{reasoning}"
                ),
            },
        ]

        result = self.backend.generate(messages)

        if not isinstance(result, str):
            raise TypeError("[Gwen]: Backend must return a string.....")

        result = result.strip()

        if not result:
            return GwenResult(
                approved=False,
                reasoning=reasoning,
                critique="Gwen returned an empty review",
            )

        approved = self._parse_approval(result)
        critique = self._parse_critique(result) or result

        return GwenResult(
            approved=approved,
            reasoning=reasoning,
            critique=critique,
        )

    @staticmethod
    def _parse_approval(result: str) -> bool:
        for line in result.splitlines():
            normalized = line.strip().lower()
            if normalized.startswith("approved:"):
                value = normalized.split(":", 1)[1].strip()
                return value == "true"
        return False

    @staticmethod
    def _parse_critique(result: str) -> str:
        for line in result.splitlines():
            normalized = line.strip().lower()
            if normalized.startswith("critique:"):
                return line.split(":", 1)[1].strip()
        return ""
